name: baseapp
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev



version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_localizations:
    sdk: flutter
  # shared_preferences: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
      - assets/images/background.jpg
      - assets/images/cat_login.png

  fonts:
    - family: Akatab
      fonts:
        - asset: assets/fonts/Akatab-Regular.ttf
        - asset: assets/fonts/Akatab-Bold.ttf
          weight: 700
    - family: Kameron
      fonts:
        - asset: assets/fonts/Kameron-Regular.ttf
        - asset: assets/fonts/Kameron-Bold.ttf
          weight: 700
    - family: Karla
      fonts:
        - asset: assets/fonts/Karla-variableFont_wght.ttf
          weight: 700
